#!/usr/bin/env python3
"""Regenerate champions-seed.json from Riot's Data Dragon + curated overrides.

Data Dragon is the source of truth for the *full* champion roster (id, name, class
tags) but does NOT publish positions (roles) or a reliable hard-CC flag, so those
come from champion-overrides.json. damageType is taken from the override when given,
otherwise derived from class tags / the attack-vs-magic ratings.

The committed champions-seed.json is the offline baseline loaded by ChampionRepository;
DataDragonService applies the same merge at runtime to stay current. Re-run after a
patch:  python3 backend/tools/generate_champion_seed.py

No Riot API key needed - Data Dragon is public static data.
"""
from __future__ import annotations

import json
import urllib.request
from pathlib import Path

DDRAGON = "https://ddragon.leagueoflegends.com"
RES = Path(__file__).resolve().parent.parent / "src" / "main" / "resources" / "data"
OVERRIDES_FILE = RES / "champion-overrides.json"
SEED_FILE = RES / "champions-seed.json"

TAG_MAP = {
    "Fighter": "FIGHTER",
    "Tank": "TANK",
    "Mage": "MAGE",
    "Assassin": "ASSASSIN",
    "Marksman": "MARKSMAN",
    "Support": "SUPPORT",
}


def fetch_json(url: str):
    with urllib.request.urlopen(url, timeout=30) as resp:
        return json.load(resp)


def latest_version() -> str:
    return fetch_json(f"{DDRAGON}/api/versions.json")[0]


def derive_damage_type(tags: list[str], info: dict) -> str:
    if "Marksman" in tags and "Mage" not in tags:
        return "PHYSICAL"
    if "Mage" in tags and "Marksman" not in tags:
        return "MAGIC"
    attack = info.get("attack", 0)
    magic = info.get("magic", 0)
    if magic > attack:
        return "MAGIC"
    if attack > magic:
        return "PHYSICAL"
    return "MIXED"


def derive_roles(tags: list[str]) -> list[str]:
    """A safe single-role fallback so every champion is queryable by role."""
    if "Support" in tags:
        return ["UTILITY"]
    if "Marksman" in tags:
        return ["BOTTOM"]
    if "Assassin" in tags or "Mage" in tags:
        return ["MIDDLE"]
    if "Tank" in tags or "Fighter" in tags:
        return ["TOP"]
    return ["MIDDLE"]


def main() -> None:
    overrides_doc = json.loads(OVERRIDES_FILE.read_text())
    overrides = {o["id"]: o for o in overrides_doc["overrides"]}

    version = latest_version()
    champ_doc = fetch_json(f"{DDRAGON}/cdn/{version}/data/en_US/champion.json")

    champions = []
    for entry in champ_doc["data"].values():
        cid = int(entry["key"])
        dd_tags = entry.get("tags", [])
        tags = [TAG_MAP[t] for t in dd_tags if t in TAG_MAP]
        ov = overrides.get(cid, {})
        champions.append({
            "id": cid,
            "name": entry["name"],
            "roles": ov.get("roles") or derive_roles(dd_tags),
            "damageType": ov.get("damageType") or derive_damage_type(dd_tags, entry.get("info", {})),
            "tags": tags,
            "cc": ov.get("cc", False),
        })

    champions.sort(key=lambda c: c["id"])
    curated = sum(1 for c in champions if c["id"] in overrides)
    doc = {
        "_comment": (
            f"GENERATED by tools/generate_champion_seed.py from Data Dragon {version}. "
            f"Full roster of {len(champions)} champions ({curated} with curated roles/cc). "
            "Do not hand-edit: change champion-overrides.json and regenerate."
        ),
        "version": version,
        "champions": champions,
    }
    SEED_FILE.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n")
    print(f"Wrote {len(champions)} champions (Data Dragon {version}) to {SEED_FILE}")


if __name__ == "__main__":
    main()
