package gg.leaguetool.champion;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Loads static champion metadata from the bundled seed and serves fast lookups by id, name and role.
 *
 * <p>The bundled seed is the full roster (generated by {@code tools/generate_champion_seed.py} from
 * Data Dragon + curated overrides) and is the always-available offline baseline. {@link DataDragonService}
 * can {@link #refresh(java.util.List) refresh} it from Riot's static data at runtime without a restart.
 */
@Component
public class ChampionRepository {

    private volatile List<Champion> all;
    private volatile Map<Integer, Champion> byId;
    private volatile Map<String, Champion> byName;

    public ChampionRepository(ObjectMapper objectMapper) {
        index(load(objectMapper));
    }

    /**
     * Atomically replaces the in-memory roster (used by {@code DataDragonService} to refresh from
     * Riot's static data without a restart). Reads always see a fully-built, consistent snapshot.
     */
    public void refresh(List<Champion> champions) {
        index(champions);
    }

    private void index(List<Champion> champions) {
        List<Champion> copy = List.copyOf(champions);
        this.byId = copy.stream()
                .collect(Collectors.toUnmodifiableMap(Champion::id, Function.identity(), (a, b) -> a));
        this.byName = copy.stream()
                .collect(Collectors.toUnmodifiableMap(
                        c -> c.name().toLowerCase(Locale.ROOT), Function.identity(), (a, b) -> a));
        this.all = copy;
    }

    private static List<Champion> load(ObjectMapper mapper) {
        try (InputStream in = new ClassPathResource("data/champions-seed.json").getInputStream()) {
            SeedFile seed = mapper.readValue(in, SeedFile.class);
            return List.copyOf(seed.champions());
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to load champion seed data", e);
        }
    }

    public List<Champion> all() {
        return all;
    }

    public Optional<Champion> byId(int id) {
        return Optional.ofNullable(byId.get(id));
    }

    public Optional<Champion> byName(String name) {
        return name == null ? Optional.empty()
                : Optional.ofNullable(byName.get(name.toLowerCase(Locale.ROOT)));
    }

    public List<Champion> byRole(Role role) {
        return all.stream().filter(c -> c.playsRole(role)).toList();
    }

    /** Resolves a champion name for an id, falling back to a placeholder for ids not in the seed. */
    public String nameOf(int championId) {
        Champion c = byId.get(championId);
        return c != null ? c.name() : "Champion " + championId;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    private record SeedFile(List<Champion> champions) {
    }
}
