-- Baseline schema for crawled match data and the computed draft aggregates.
-- Generated from the JPA entities (Hibernate's own DDL) so ddl-auto=validate matches it exactly.
-- Identity columns use GENERATED BY DEFAULT AS IDENTITY to match GenerationType.IDENTITY.

CREATE TABLE matches (
    match_id      VARCHAR(32)  NOT NULL,
    queue_id      INTEGER      NOT NULL,
    game_version  VARCHAR(255),
    game_duration BIGINT       NOT NULL,
    game_creation BIGINT       NOT NULL,
    winning_team  INTEGER,
    ingested_at   TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT matches_pkey PRIMARY KEY (match_id)
);

CREATE TABLE match_participant (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    match_id      VARCHAR(255),
    puuid         VARCHAR(255),
    champion_id   INTEGER NOT NULL,
    team_id       INTEGER NOT NULL,
    team_position VARCHAR(255),
    win           BOOLEAN NOT NULL,
    kills         INTEGER NOT NULL,
    deaths        INTEGER NOT NULL,
    assists       INTEGER NOT NULL,
    CONSTRAINT match_participant_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_participant_match ON match_participant (match_id);
CREATE INDEX idx_participant_champion ON match_participant (champion_id);

CREATE TABLE champion_role_stat (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    champion_id INTEGER NOT NULL,
    role_name   VARCHAR(255),
    games       BIGINT  NOT NULL,
    wins        BIGINT  NOT NULL,
    CONSTRAINT champion_role_stat_pkey PRIMARY KEY (id),
    CONSTRAINT uk_role_stat UNIQUE (champion_id, role_name)
);

CREATE TABLE champion_pair_stat (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    champion_low  INTEGER NOT NULL,
    champion_high INTEGER NOT NULL,
    games         BIGINT  NOT NULL,
    wins          BIGINT  NOT NULL,
    CONSTRAINT champion_pair_stat_pkey PRIMARY KEY (id),
    CONSTRAINT uk_pair_stat UNIQUE (champion_low, champion_high)
);

CREATE TABLE champion_matchup_stat (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    champion_id          INTEGER NOT NULL,
    opponent_champion_id INTEGER NOT NULL,
    role_name            VARCHAR(255),
    games                BIGINT  NOT NULL,
    wins                 BIGINT  NOT NULL,
    CONSTRAINT champion_matchup_stat_pkey PRIMARY KEY (id),
    CONSTRAINT uk_matchup_stat UNIQUE (champion_id, opponent_champion_id, role_name)
);
